import './globals.css';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

const ibmPlexSerif = localFont({
  src: [
    {
      path: '../../public/fonts/IBM_Plex_Serif/IBMPlexSerif-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-ibm-plex-serif',
});

const sansation = localFont({
  src: [
    {
      path: '../../public/fonts/Sansation/Sansation-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-sansation',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/images/logo-black.svg" />
      <body className={`${ibmPlexSerif.variable} ${sansation.variable}`}>
        {children}
      </body>
    </html>
  );
}
